"use client";
import Link from "next/link";
import { type ChangeEvent, useRef, useState } from "react";
import { Eye, FilePlus2, Loader2, Lock, Pencil, Presentation, Trash2, Upload } from "lucide-react";
import { useRouter } from "next/navigation";
import { SlideView } from "./SlideView";

type Deck={id:string;title:string;description:string|null;visibility:string;sourceType?:string;owner:{name:string|null;email:string};_count:{slides:number;viewLogs:number};ownerId:string;slides?:{content:unknown}[]};
export function DeckManager({decks,canCreate,userId,isAdmin}:{decks:Deck[];canCreate:boolean;userId:string;isAdmin:boolean}){const router=useRouter();const[open,setOpen]=useState(false);const[error,setError]=useState("");const fileRef=useRef<HTMLInputElement>(null);const pending=useRef<{id:string;sourceType?:string}|null>(null);const[updating,setUpdating]=useState<string|null>(null);
 function startUpdate(d:Deck){pending.current={id:d.id,sourceType:d.sourceType};if(fileRef.current){fileRef.current.accept=d.sourceType==="PPTX"?".pptx":".md,.markdown";fileRef.current.value="";fileRef.current.click()}}
 async function onFile(e:ChangeEvent<HTMLInputElement>){const file=e.target.files?.[0];const d=pending.current;if(!file||!d)return;setUpdating(d.id);try{let r:Response;if(d.sourceType==="PPTX"){const fd=new FormData();fd.append("file",file);r=await fetch(`/api/decks/${d.id}/import/pptx`,{method:"POST",body:fd})}else{if(!/\.(md|markdown)$/i.test(file.name)){alert("請選擇 .md / .markdown 檔");return}const text=await file.text();r=await fetch(`/api/decks/${d.id}/markdown`,{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({markdown:text})})}if(!r.ok){alert((await r.json().catch(()=>({}))).error||"更新失敗");return}router.refresh()}catch{alert("更新失敗，請稍後再試")}finally{setUpdating(null);pending.current=null;if(fileRef.current)fileRef.current.value=""}}
 async function create(formData:FormData){setError("");const response=await fetch("/api/decks",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(Object.fromEntries(formData))});if(!response.ok){setError((await response.json()).error);return;}const deck=await response.json();router.push(`/decks/${deck.id}/edit`)}
 async function remove(id:string){if(!confirm("確定永久刪除這份簡報？此操作無法復原。"))return;const r=await fetch(`/api/decks/${id}`,{method:"DELETE"});if(r.ok)router.refresh();else alert((await r.json()).error)}
 return <><input ref={fileRef} type="file" hidden onChange={onFile}/><div className="section-head"><div><h1>簡報工作區</h1><p className="muted">建立、編輯與追蹤你的內容。</p></div>{canCreate&&<button className="btn" onClick={()=>setOpen(true)}><FilePlus2 size={18}/>新增簡報</button>}</div>
 {decks.length?<div className="grid">{decks.map(d=><article className="card deck-card" key={d.id}><Link href={`/d/${d.id}`}><div className="deck-cover">{d.slides?.[0]?<SlideView content={d.slides[0].content}/>:<Presentation size={48}/>}</div></Link><div className="deck-body"><div className="deck-meta"><span className="badge">{d.visibility==="PASSWORD"?<Lock size={12}/>:<Eye size={12}/>} {d.visibility}</span><span>{d._count.slides} 頁 · {d._count.viewLogs} 次瀏覽</span></div><h3>{d.title}</h3><p className="muted">{d.description||`由 ${d.owner.name||d.owner.email} 建立`}</p><div className="actions"><Link className="btn small" href={`/d/${d.id}`}>播放</Link>{(d.ownerId===userId||isAdmin)&&<>{d.sourceType!=="PPTX"&&<Link className="btn secondary small" href={`/decks/${d.id}/edit`}><Pencil size={14}/>編輯</Link>}<button className="btn secondary small" onClick={()=>startUpdate(d)} disabled={updating===d.id} title={d.sourceType==="PPTX"?"上傳新的 .pptx 覆蓋":"上傳新的 .md 覆蓋"}>{updating===d.id?<Loader2 size={14} className="spin"/>:<Upload size={14}/>}更新</button><button className="btn secondary small" aria-label="刪除" onClick={()=>remove(d.id)}><Trash2 size={14}/></button></>}</div></div></article>)}</div>:<div className="empty"><Presentation size={42}/><h3>目前沒有可顯示的簡報</h3><p>{canCreate?"建立第一份簡報，開始整理你的想法。":"請等待管理員將你的角色升級為 User。"}</p></div>}
 {open&&<div className="modal-backdrop" onMouseDown={()=>setOpen(false)}><div className="modal" onMouseDown={e=>e.stopPropagation()}><h2>新增簡報</h2><form action={create}><div className="field"><label>標題</label><input className="input" name="title" required maxLength={150}/></div><div className="field"><label>描述</label><textarea className="input" name="description" maxLength={1000}/></div><div className="field"><label>可見性</label><select className="input" name="visibility" defaultValue="PRIVATE"><option value="PRIVATE">私人</option><option value="PUBLIC">公開（登入者）</option><option value="UNLISTED">不公開列表</option></select></div>{error&&<p className="error">{error}</p>}<div className="actions"><button className="btn" type="submit">建立</button><button className="btn secondary" type="button" onClick={()=>setOpen(false)}>取消</button></div></form></div></div>}</>}
